name: pollen_tracker
description: "Sirius: Pollen Tracker."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1

  # Logger
  logger: ^2.1.0
  pretty_dio_logger: ^1.3.1

  # State-manager
  flutter_bloc: ^8.1.4

  # Routing
  go_router: ^13.2.1

  # Local-storage
  isar: ^3.1.0+1

  # Networking
  dio: ^5.4.1

  # DI
  get_it: ^7.6.7
  injectable: ^2.3.5

  # Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_crashlytics: ^3.4.19
  path_provider: ^2.1.2
  isar_flutter_libs: ^3.1.0+1
  csv: ^6.0.0
  rxdart: ^0.27.7
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.0.9
  collection: ^1.18.0
  overlay_support: ^2.1.0

dev_dependencies:
  injectable_generator: ^2.4.2
  isar_generator: ^3.1.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Building
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  # Local assets, used for mocks
  assets:
    - assets/
    - assets/images/svg/
    - assets/icon/
  uses-material-design: true
  generate: true 
